#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.

image: gradle:jdk17-alpine

pipelines:
  default:
    - step:
        name: build
        caches:
          - gradle
        script:
          - gradle clean build -x test
        artifacts:
          - build/libs/**
        after-script:
          - pipe: atlassian/checkstyle-report:0.3.0
    - step:
        name: push
        services:
          - docker
        caches:
          - docker
        script:
          - docker build -t mac-oauth2/api:$BITBUCKET_BUILD_NUMBER .
#          - docker tag mac-oauth2/api:$BITBUCKET_BUILD_NUMBER 249145062117.dkr.ecr.ap-northeast-2.amazonaws.com/mac-oauth2/api:$BITBUCKET_BUILD_NUMBER
          - docker images
          - pipe: atlassian/aws-ecr-push-image:2.0.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              IMAGE_NAME: mac-oauth2/api
              TAGS: $BITBUCKET_BUILD_NUMBER