spring:
  profiles:
    default: local

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

hydra:
  base-path: http://localhost:4445
---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: aws

hydra:
  base-path: http://52.79.232.182:4445